import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr, formatdate, make_msgid


def _build_html(date: datetime, page_url: str, preview_articles: list[dict]) -> str:
    date_label = date.strftime("%A, %B %#d, %Y")
    articles_html = ""
    for a in preview_articles:
        pub = a["published"].astimezone().strftime("%b %#d, %#I:%M %p") if a.get("published") else ""
        articles_html += f"""
        <div style="margin-bottom:24px;padding-bottom:24px;border-bottom:1px solid #e5e7eb;">
          <div style="font-size:12px;color:#6b7280;margin-bottom:4px;">{a.get('category','')} &middot; {a.get('source','')} &middot; {pub}</div>
          <a href="{a['link']}" style="font-size:17px;font-weight:600;color:#111827;text-decoration:none;">{a['title']}</a>
          <p style="margin:8px 0 0;font-size:14px;color:#374151;line-height:1.6;">{a.get('summary','')}</p>
        </div>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:600px;margin:32px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1);">
    <div style="background:#1d4ed8;padding:24px 32px;">
      <div style="font-size:12px;color:#bfdbfe;text-transform:uppercase;letter-spacing:.08em;">Daily Digest</div>
      <div style="font-size:24px;font-weight:700;color:#fff;margin-top:4px;">{date_label}</div>
    </div>
    <div style="padding:24px 32px;">
      <a href="{page_url}" style="display:block;background:#1d4ed8;color:#fff;text-align:center;padding:12px 24px;border-radius:6px;font-weight:600;font-size:15px;text-decoration:none;margin-bottom:32px;">
        View Full Digest &rarr;
      </a>
      <div style="font-size:13px;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:.06em;margin-bottom:16px;">Today's Highlights</div>
      {articles_html}
    </div>
    <div style="background:#f3f4f6;padding:16px 32px;font-size:12px;color:#9ca3af;text-align:center;">
      Generated by rss-digest &middot; To stop receiving, disable the Task Scheduler task.
    </div>
  </div>
</body>
</html>"""


def _build_text(date: datetime, page_url: str, preview_articles: list[dict]) -> str:
    date_label = date.strftime("%A, %B %#d, %Y")
    lines = [f"Daily Digest — {date_label}", f"View full digest: {page_url}", "", "Highlights:", ""]
    for a in preview_articles:
        lines.append(f"[{a.get('category','')}] {a['title']}")
        lines.append(a.get("summary", ""))
        lines.append(a["link"])
        lines.append("")
    return "\n".join(lines)


def send(
    date: datetime,
    page_url: str,
    preview_articles: list[dict],
    gmail_address: str,
    app_password: str,
    to_email: str,
) -> None:
    subject = date.strftime("Daily Digest — %a %b %#d")
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = formataddr(("RSS Digest", gmail_address))
    msg["To"] = to_email
    # Date and Message-ID are not added automatically by MIMEMultipart; without
    # them Gmail/receiving servers are more likely to flag the mail as spam.
    msg["Date"] = formatdate(localtime=True)
    msg["Message-ID"] = make_msgid(domain=gmail_address.split("@")[-1])
    msg.attach(MIMEText(_build_text(date, page_url, preview_articles), "plain"))
    msg.attach(MIMEText(_build_html(date, page_url, preview_articles), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(gmail_address, app_password)
        smtp.sendmail(gmail_address, to_email, msg.as_string())
